### PR TITLE
XFAIL Kickstarter and ReactiveSwift targets affected by SR-13548

### PR DESCRIPTION
**Pull request by xedin**
This is only applicable to `Debug` configuration.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by shahmishal — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Could be superseded by https://github.com/apple/swift/pull/33946

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Pull request merged**
