### PR TITLE
Update swift-nio revision to include source fix

### PR DESCRIPTION
**Pull request by justice-adams-apple**
### Pull Request Description

* Updated swift-nio revision used by the compat suite to include fix for rdar://81180448, which was determined to be a project source error. This will allow us to test the project properly going forward.

ToDo: 
- [x] ~This uncovered a new build error with the 4.2 version. I will create a git issue and link it here~.

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
Per https://github.com/apple/swift-nio/issues/2241, swift-nio no longer supports 4.x, removing revision from suite.

**Comment by justice-adams-apple** [comment]
Tagging @Lukasa for visibility

**Review by Lukasa — APPROVED** [review]

**Comment by Lukasa** [comment]
LGTM.

**Review by shahmishal — APPROVED** [review]

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
Currently causing a compiler crash: https://github.com/apple/swift/issues/60797 

Will merge this once it's fixed and the xfail can be removed

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
https://github.com/apple/swift-source-compat-suite/pull/773

**Pull request closed without merging**
