### PR TITLE
[Add] ACHNBrowserUI

### PR DESCRIPTION
**Pull request by Dimillian**
### Pull Request Description

Add [ACHNBrowserUI](https://github.com/Dimillian/ACHNBrowserUI) a full featured SwiftUI application

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by Dimillian** [comment]
Anything I should do?

**Comment by clackary** [comment]
Ah, this isn't related to your changes at all. Restarting testing.

**Comment by clackary** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
It's the silly header error again, ugh.

```
'/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator13.4.sdk/usr/include/AvailabilityInternal.h': Operation not permitted
#include <AvailabilityInternal.h>
         ^
```

I thought that was already fixed. Let's see what we can do here...

Btw, is there a typo in the name (ACHNBrowserUI instead of AC**NH**BrowserUI)?

**Comment by Dimillian** [comment]
Busted.... yes I’ve made a typo when I created the repository and the project and now it’s too late haha...

**Comment by varungandhi-apple** [comment]
I think this has been fixed; bunch of PRs against apple/swift are passing, instead of falling over with the header error.

@swift-ci please clean test

**Comment by varungandhi-apple** [comment]
Oh boy, I was not expecting this to trigger a crash in the compiler. Filed [SR-12824](https://bugs.swift.org/browse/SR-12824).

**Comment by Dimillian** [comment]
So basically, we’re actually seeing a regression then 😄

**Comment by varungandhi-apple** [comment]
It's not clear if it's a regression. For example, we disable assertions in the toolchain shipping in Xcode, but the compiler being used in the tests here has assertions on. I think (not 100% sure) that this is also true for some verifier passes. Since the crash is happening during a verifier pass, it's possible that this issue is present even in shipping toolchains, but it isn't getting triggered because it's off by default. If you want to try it out, you could try building the project using additional compiler flags `-Xfrontend -sil-verify-all`.

**Comment by Dimillian** [comment]
Awesome I’ll try, maybe I’m doing something a bit off and I can fix it for this PR to pass.

**Comment by Dimillian** [comment]
Still passing the build with those flags on Xcode Version 11.4.1 (11E503a)
Screenshot 2020-05-16 at 13 11 33

**Comment by varungandhi-apple** [comment]
Thanks for checking, then that's probably a regression.

**Comment by varungandhi-apple** [comment]
Looks like this was just fixed yesterday: https://github.com/apple/swift/pull/31832

@swift-ci please clean test

**Comment by Dimillian** [comment]
Nice! I'll also update both MovieSwiftUI and this project commit once this PR pass. Quite a lot of more SwiftUI in both projects.

**Comment by varungandhi-apple** [comment]
The failure right now is when building another project (`exercism-swift`), not this one. Let's see what needs to be done to fix the `exercise-swift` issue...

**Comment by varungandhi-apple** [comment]
Cannot reproduce the `exercism-swift` issue locally. 😕

@swift-ci please test

**Comment by Dimillian** [comment]
Maybe one more time ? :p

**Comment by xedin** [comment]
@swift-ci please test

**Comment by Dimillian** [comment]
🥳  WOOOOW

**Comment by varungandhi-apple** [comment]
🚢

**Pull request merged**
