### PR TITLE
Xfail swift-futures

### PR DESCRIPTION
**Pull request by clackary**
https://bugs.swift.org/browse/SR-14090

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
@clackary Were you able to reproduce this failure locally? I don't see any error in the build log.

**Comment by clackary** [comment]
Yes, I was able to reproduce locally, the frontend crashed. There’s a log attached to the radar.

**Comment by shahmishal** [comment]
If possible, can you attach it to bugs.swift.org?

**Comment by clackary** [comment]
Sure, I can do that.

**Pull request merged**
