### PR TITLE
Adding config for Swift 4 support

### PR DESCRIPTION
**Pull request by ankurp**
### Pull Request Description

Updating config for Dollar project as it works with Swift 4

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by lplarson** [comment]
@swift-ci test

**Comment by lplarson** [comment]
fatal: reference is not a tree: 9e102ed702045a09eae77b16d223160a66c3f8bc

**Comment by clackary** [comment]
Also unable to checkout the 4.0 hash
`fatal: reference is not a tree: 04ae84dbaf423214c644590cbe0d837edfbfd411`

**Comment by clackary** [comment]
Hi, any updates here? Could you double-check your 3.1 and 4.0 hashes when you get a chance?

**Comment by clackary** [comment]
@swift-ci please test

**Comment by ankurp** [comment]
@clackary Good to merge

**Comment by clackary** [comment]
Thanks @ankurp

**Pull request merged**
