### PR TITLE
Removed xfail.

### PR DESCRIPTION
**Pull request by nate-chandler**
Updated fail to match compiler change.

### CODE REVIEW

**Comment by nate-chandler** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/60756

@swift-ci please test

**Comment by nate-chandler** [comment]
Cross-repo testing didn't seem to take, but the project UPASSed over on that PR.  Testing again.

**Comment by nate-chandler** [comment]
@swift-ci please test

**Comment by nate-chandler** [comment]
cc: @shahmishal @justice-adams-apple

**Review by justice-adams-apple — APPROVED** [review]
LGTM. Thanks @nate-chandler . Should we close zhttps://github.com/apple/swift/issues/60627 ?

**Pull request merged**
