### PR TITLE
XFail projects impacted by rdar://113121424

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Review by justice-adams-apple — APPROVED** [review]
Should we use a swift issue rather than a radar to track this?

**Comment by xedin** [comment]
If that's the convention then absolutely!

**Comment by xedin** [comment]
Looks like we have a fix already I'll just wait - https://github.com/apple/swift/pull/67634

**Pull request closed without merging**
