### PR TITLE
[Add] MovieSwiftUI

### PR DESCRIPTION
**Pull request by Dimillian**
### Pull Request Description
Add [MovieSwiftUI](https://github.com/Dimillian/MovieSwiftUI)
### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Build log can be found [here](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/491/artifact/swift-source-compat-suite/FAIL_MovieSwift-MovieSwift-MovieSwift.xcodeproj_5.1_BuildXcodeProjectTarget_MovieSwift_generic-platform-iOS.log).

Looks like it's running into an issue with the sandbox. Looking into it to see if I can get some more details.

**Comment by Dimillian** [comment]
Should I do anything within the project?

**Comment by clackary** [comment]
I don't think a project-side change is necessary quite yet. It passes `project_precommit_check` for me locally, so I'm looking into the interaction with the sandbox.

**Comment by Dimillian** [comment]
I've updated to a new commit, to ensure I match my correct internal SPM dependency

**Comment by clackary** [comment]
I'll start another round of testing, but would you mind moving the MovieSwiftUI entry up to roughly line 1417? We try to keep these projects sorted by `path`.

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by Dimillian** [comment]
Done :)

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Quick update here. I filed a bug report for the sandbox issue: https://bugs.swift.org/browse/SR-11210

It's possible the sandbox issue is covering up something else. I'm going to see if I can test it locally without the sandbox to see if we hit anything. If things look good there, we may want to just add an xfail so we can get it checked in while working out the sandbox problem.

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by Dimillian** [comment]
Anything I can do? I've also made updated to the project and its swift package dependency so it can compile without warnings on Swift 5.2. Might I update the commit ref?

**Comment by varungandhi-apple** [comment]
@Dimillian thanks for hanging in. That would certainly be helpful. If you look at the last failure [here](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/554/artifact/swift-source-compat-suite/FAIL_MovieSwift-MovieSwift-MovieSwift.xcodeproj_5.1_BuildXcodeProjectTarget_MovieSwift_generic-platform-iOS.log):

```
Resolve Package Graph

Fetching https://github.com/Dimillian/SwiftUIFlux.git

xcodebuild: error: Could not resolve package dependencies:
  sandbox-exec: sbpl1:38:21: unable to open system.sb
	(string-append "unable to open " path)
```

that seems a but cryptic and it isn't really clear to me what the problem was. Unless it rings any bells for you (maybe you've seen a similar error before?)... I'll try to debug that when I have some spare time later. We really would love to have MovieSwiftUI in the source compat suite sooner rather than later. 😄

**Comment by clackary** [comment]
@Dimillian Yes, a newer commit ref might help if you’ve updated the dependencies. I’ve also been able to get it building locally without issue as well, but I’ve run into issues when applying the sandbox rules.

I’ll try to sync up with @varungandhi-apple today to see if we can come up with a plan.

**Comment by Dimillian** [comment]
Is there a way for me to simulate the CI sandbox rule on my machine?

**Comment by clackary** [comment]
I don't think the exact rules we use are public for security concerns, but the basic idea of the sandbox rules is to limit write access to only within swift-source-compat-suite. You might be able to roll your own .sb file with local paths to simulate it, but that can get hairy.

I've opened #408 as a possible solution here. Turns out there's an xcodebuild flag that will disable the package support sandbox, and hopefully prevent the collision.

**Comment by Dimillian** [comment]
I've updated to the latest commit, and updated the Swift version to 5.2

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
I think there are two kinds of compiler failures going on:

1. The protocol conformance `DispatchQueue : Scheduler` is not being found. This one is getting triggered by MovieSwiftUI. This is being tracked in [SR-12077](https://bugs.swift.org/browse/SR-12077).
2. There are one or more bugs in the name mangler. These are getting triggered by ReactiveKit, swift-nio and others. Trying to find if this has been reported.

**Comment by varungandhi-apple** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by varungandhi-apple** [comment]
Thanks for merging this! 🎉

**Comment by Dimillian** [comment]
Woooow thanks !!!! 🎉

**Pull request merged**
