### PR TITLE
For JSQCoreDataKit drop building Swift 3, and update to tip for Swift 4

### PR DESCRIPTION
**Pull request by tkremenek**
- Drop building Swift 3 variant of this project.
- Update to tip of `master` for building project in Swift 4 mode.

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by clackary** [comment]
Link to [CI log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/224/artifact/swift-source-compat-suite/FAIL_JSQCoreDataKit-JSQCoreDataKit.xcodeproj_4.0_BuildXcodeProjectTarget_JSQCoreDataKit-iOS_generic-platform-iOS.log). Looks like a new dependency.
```
    /bin/sh -c /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/JSQCoreDataKit/build/JSQCoreDataKit.build/Release-iphoneos/JSQCoreDataKit-iOS.build/Script-882986082006938A008DD41B.sh
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/JSQCoreDataKit/scripts/lint.sh: line 4: swiftlint: command not found

    Error: SwiftLint not installed!
    Download from https://github.com/realm/SwiftLint,
    or brew install swiftlint.
```

**Comment by jessesquires** [comment]
Thanks @tkremenek !

@clackary Ugh, sorry about that. I'll fix this, it's not a hard dependency.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@jessesquires commit `772920fef79fac26cf7a2c3d58f32e739249c5d5` has been removed recently?

**Comment by jessesquires** [comment]
@shahmishal sorry about that! that was development branch that just deleted after merging to master. going to send you a new PR now to update this

**Comment by jessesquires** [comment]
See #286

**Pull request merged**
