### PR TITLE
Cperf suite and baselines

### PR DESCRIPTION
**Pull request by graydon**
This adds a new project file with a small, quick subset of source compat projects for use as a compilation-performance ("cperf") smoketest, alone with CSV baselines for some select counter values of those projects. This is for use in various forthcoming swift-ci behaviours, as well as quick iteration on swift compiler developer workstations.

### CODE REVIEW

**Comment by graydon** [comment]
@swift-ci Please test source compatibility

**Comment by graydon** [comment]
@swift-ci test source compatibility

**Comment by graydon** [comment]
@swift-ci Please test

**Comment by graydon** [comment]
@swift-ci please test

**Comment by lplarson** [comment]
LGTM

**Pull request merged**
