### PR TITLE
Update Surge to Swift 4

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
We need to update scheme of the project to be 

```
Schemes:
        Surge-iOS
        Surge-macOS
        Surge-tvOS
        Surge-watchOS
```

**Comment by clackary** [comment]
Yep, running a test locally to verify schemes are correct.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
