### PR TITLE
UnXFAIL GRDB. SR-5235.

### PR DESCRIPTION
**Pull request by atrick**
@lplarson

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by lplarson** [comment]
You'll need to remove the comma at the end of the following line. JSON doesn't allow trailing commas.

"configuration": "release",

**Comment by atrick** [comment]
@swift-ci test source compatibility

**Comment by lplarson** [comment]
Looks good. Thanks!

**Pull request merged**
