### PR TITLE
Add Moya

### PR DESCRIPTION
**Pull request by aksswami**
### Pull Request Description

Replace with a description of this pull request. Instructions for adding
projects are available in the README.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [X] be an *Xcode* or *swift package manager* project
- [X] support building on either Linux or macOS
- [X] target Linux, macOS, or iOS/tvOS/watchOS device
- [X] be contained in a publicly accessible git repository
- [X] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [X] have maintainers who will commit to resolve issues in a timely manner
- [X] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [X] add value not already included in the suite
- [X] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [ ] pass ./check script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by aksswami** [comment]
Need help with this. As I am getting error in `./check Moya` step. And not able to get much information from the logs. I am attaching logs via a gist here.

https://gist.github.com/aksswami/446238a766b4ba0573d3653fe59502f6

If would be great, if someone can help me debugging this issue.

**Comment by aksswami** [comment]
@swift-ci Please test source compatibility

**Comment by lplarson** [comment]
This appears to be the problem:
<unknown>:0: error: unable to build node: '/Users/XXX/Developer/iOSWorkSpace/swift-source-compat-suite/project_cache/Moya/.build/release/Result.swiftmodule' (node is produced by multiple commands; e.g., '<RxMoya.module>' and '<Result.module>')
<unknown>:0: error: unable to build node: '/Users/XXX/Developer/iOSWorkSpace/swift-source-compat-suite/project_cache/Moya/.build/release/Result.build/ResultProtocol.swift.o' (node is produced by multiple commands; e.g., '<RxMoya.module>' and '<Result.module>')
<unknown>:0: error: unable to build node: '/Users/XXX/Developer/iOSWorkSpace/swift-source-compat-suite/project_cache/Moya/.build/release/Result.build/Result.swift.o' (node is produced by multiple commands; e.g., '<RxMoya.module>' and '<Result.module>')

**Comment by BasThomas** [comment]
Not really sure where this is coming from, @aksswami. Maybe the fact that we have multiple (sub)projects that all try to build `Result`? Not sure how to proceed.

**Comment by BasThomas** [comment]
@aksswami, we've changed some things in our SwiftPM setup. Can you see if the `./check` script run doesn't error now?

**Comment by aksswami** [comment]
Sure. I will check and update here. @BasThomas

**Comment by lplarson** [comment]
@BasThomas I'm still seeing:

Moya/.build/release.yaml:121:3: error: duplicate command in 'commands' map
  "<Result.module>":
  ^~~~~~~~~~~~~~~~~
warning: The target Supporting Files in package Moya does not contain any valid source files.
error: terminated(1)

**Comment by lplarson** [comment]
Updated to the latest project hash and everything worked. Thanks!

**Comment by BasThomas** [comment]
🙌

**Comment by sunshinejr** [comment]
To sum up what (probably) was wrong in our case: `.git` suffix mismatch in `Package.swift`. Please take a look at [Moya#1093](https://github.com/Moya/Moya/pull/1093) for detailed explanation.

**Comment by aksswami** [comment]
@lplarson @sunshinejr  🙌

**Pull request merged**
