### PR TITLE
Update swift-argument-parser to 0.0.6

### PR DESCRIPTION
**Pull request by owenv**
Corresponding swift update-checkout PR: https://github.com/apple/swift/pull/31790

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci test

**Comment by owenv** [comment]
@DougGregor do you mind merging this on my behalf if the config changes look ok?

**Comment by shahmishal** [comment]
Next time we update the tag version, please also tag me in the PR

**Comment by owenv** [comment]
@shahmishal will do, sorry about that. I wasn't aware CI needed updates.

**Pull request merged**
