### PR TITLE
Remove resolved xfails for swift-testing

### PR DESCRIPTION
**Pull request by stmontgomery**
### Pull Request Description

Resolve 3 xfails for swift-testing which have now been resolved:

- apple/swift#69096
- apple/swift-testing#138
- apple/swift-testing#139

For context, these xfails were added in these two PRs:

- #851
- #857

I also updated the baseline commit of swift-testing since we landed a [workaround](https://github.com/apple/swift-testing/pull/125) for another Swift compiler issue.

Resolves rdar://116924612

### CODE REVIEW

**Comment by stmontgomery** [comment]
@swift-ci test

**Review by justice-adams-apple — APPROVED** [review]

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by stmontgomery** [comment]
@swift-ci test

**Comment by stmontgomery** [comment]
@swift-ci test

**Comment by stmontgomery** [comment]
@swift-ci please test

**Comment by justice-adams-apple** [comment]
@swift-ci please test

**Pull request merged**
