### PR TITLE
Add 5.2 configuration for ACHNBrowserUI

### PR DESCRIPTION
**Pull request by clackary**
### Pull Request Description

Updating ACHNBrowserUI configuration with a new 5.2 commit.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* Apache License, version 2.0
- [x] pass `./project_precommit_check` script run
```
PASS: ACHNBrowserUI, 5.2, 3f14c4, ACHNBrowserUI, generic/platform=iOS
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- ACHNBrowserUI checked successfully against Swift 5.2 ---
```

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by clackary** [comment]
Looks like the project test passed in a previous PR test, but the [build failed](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/630) for unrelated reason...
```
15:39:15 PASS: ACHNBrowserUI, 5.2, 3f14c4, ACHNBrowserUI, generic/platform=iOS
```

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with `main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
