### PR TITLE
Build tests for Swift packages

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test toolchain

**Comment by shahmishal** [comment]
@swift-ci test with toolchain

**Comment by shahmishal** [comment]
@swift-ci test

**Review by ktoso — APPROVED** [review]
Thanks!

**Comment by shahmishal** [comment]
```
07:26:48.005 Failures:
07:26:48.005   FAIL: AsyncNinja, 5.1, 7bd7ea, Swift Package
07:26:48.005   FAIL: AsyncNinja, 4.0, efc83b, Swift Package
07:26:48.005   FAIL: DNS, 5.1, 328a0c, Swift Package
07:26:48.005   FAIL: DNS, 4.0, 04ae84, Swift Package
07:26:48.005   FAIL: exercism-swift, 5.1, 3df5e4, Swift Package
07:26:48.005   FAIL: exercism-swift, 4.2, 3df5e4, Swift Package
07:26:48.005   FAIL: GRDB.swift, 5.3, d29010, Swift Package
07:26:48.005   FAIL: GRDB.swift, 5.1, d29010, Swift Package
07:26:48.005   FAIL: GRDB.swift, 5.0, 759c10, Swift Package
07:26:48.005   FAIL: GRDB.swift, 4.2, 759c10, Swift Package
07:26:48.005   FAIL: grpc-swift, 5.3, a45db1, Swift Package
07:26:48.005   FAIL: Kitura, 5.1, 8578c4, Swift Package
07:26:48.005   FAIL: Kitura, 4.0, f1c316, Swift Package
07:26:48.005   FAIL: Kronos, 5.1, bf462b, Swift Package
07:26:48.005   FAIL: Kronos, 5.0, d38491, Swift Package
07:26:48.005   FAIL: Kronos, 4.2, d38491, Swift Package
07:26:48.005   FAIL: Kronos, 4.0, d38491, Swift Package
07:26:48.005   FAIL: Lark, 5.1, b1ed2b, Swift Package
07:26:48.005   FAIL: Lark, 4.2, af39c8, Swift Package
07:26:48.005   FAIL: NetService, 5.0, 927eb1, Swift Package
07:26:48.005   FAIL: NetService, 4.2, 927eb1, Swift Package
07:26:48.005   FAIL: NonEmpty, 5.1, 6c98dc, Swift Package
07:26:48.005   FAIL: NSAttributedStringBuilder, 5.1, f651c4, Swift Package
07:26:48.005   FAIL: Perfect, 5.1, 54a669, Swift Package
07:26:48.005   FAIL: Plank, 5.1, bc8c8f, Swift Package
07:26:48.005   FAIL: Plank, 5.0, 71a3a5, Swift Package
07:26:48.005   FAIL: Plank, 4.2, 71a3a5, Swift Package
07:26:48.005   FAIL: R.swift, 5.1, 5fd4a4, Swift Package
07:26:48.005   FAIL: R.swift, 5.0, f96758, Swift Package
07:26:48.005   FAIL: R.swift, 4.2, f96758, Swift Package
07:26:48.005   FAIL: RxReactiveObjC, 5.3, ec478b, Swift Package
07:26:48.005   FAIL: RxReactiveObjC, 4.2, ec478b, Swift Package
07:26:48.005   FAIL: Serpent, 5.1, 61d72c, Swift Package
07:26:48.005   FAIL: Serpent, 4.2, 61d72c, Swift Package
07:26:48.005   FAIL: swift-algorithms, 5.2, 386460, Swift Package
07:26:48.005   FAIL: swift-argument-parser, 5.2, 41f5fe, Swift Package
07:26:48.005   FAIL: SwiftFormat, 4.2, d42194, Swift Package
07:26:48.005   FAIL: SwiftGraph, 5.1, 872092, Swift Package
07:26:48.005   FAIL: SwiftGraph, 4.2, f4948e, Swift Package
07:26:48.005   FAIL: SwiftGraph, 4.0, 6c8c5d, Swift Package
07:26:48.005   FAIL: SwiftLint, 5.1, ac8abb, Swift Package
07:26:48.005   FAIL: SwiftLint, 5.0, 60f98e, Swift Package
07:26:48.005   FAIL: SwiftLint, 4.2, 60f98e, Swift Package
07:26:48.005   FAIL: SwiftLint, 4.0, 60f98e, Swift Package
07:26:48.005   FAIL: swift-nio, 5.3, 9a992e, Swift Package
07:26:48.005   FAIL: swift-log, 5.2, 16cfcc, Swift Package
07:26:48.005   FAIL: async-http-client, 5.0, a72c5a, Swift Package
07:26:48.005   FAIL: swift-nio-http2, 5.3, 59941f, Swift Package
07:26:48.005   FAIL: swift-nio-http2, 5.0, 492a77, Swift Package
07:26:48.005   FAIL: swift-metrics, 5.2, 68e6cb, Swift Package
07:26:48.005   FAIL: swift-nio-extras, 5.3, e8d444, Swift Package
07:26:48.005   FAIL: swift-nio-extras, 5.0, 66f9a5, Swift Package
07:26:48.005   FAIL: swift-nio-extras, 4.2, 0dbd54, Swift Package
07:26:48.005   FAIL: swift-nio-ssl, 5.3, 62bf50, Swift Package
07:26:48.005   FAIL: swift-nio-ssl, 5.0, 16de4b, Swift Package
07:26:48.005   FAIL: swift-nio-ssh, 5.3, 3860f7, Swift Package
07:26:48.005   FAIL: swift-nio-transport-services, 5.3, 9fc0d3, Swift Package
07:26:48.005   FAIL: swift-crypto, 5.3, 8f4bfa, Swift Package
07:26:48.005   FAIL: swift-numerics, 5.2, ae364a, Swift Package
07:26:48.005   FAIL: swift-system, 5.2, 0627d2, Swift Package
07:26:48.005   FAIL: swift-distributed-tracing, 5.2, 7a89c9, Swift Package
07:26:48.005   FAIL: swift-cluster-membership, 5.2, 0fd434, Swift Package
07:26:48.005   FAIL: Then, 5.1, 96cbf1, Swift Package
07:26:48.005   FAIL: Then, 5.0, 3edb1c, Swift Package
07:26:48.005   FAIL: Then, 4.2, 3edb1c, Swift Package
07:26:48.005   FAIL: vapor_console, 5.1, fcd8c1, Swift Package
07:26:48.005   FAIL: vapor_console, 5.0, 5b9796, Swift Package
07:26:48.005   FAIL: vapor_console, 4.2, 5b9796, Swift Package
07:26:48.005   FAIL: vapor_core, 5.1, c64f63, Swift Package
07:26:48.005   FAIL: vapor_core, 5.0, 08a576, Swift Package
07:26:48.005   FAIL: vapor_core, 4.2, 08a576, Swift Package
07:26:48.005   FAIL: vapor_service, 5.1, 869826, Swift Package
07:26:48.005   FAIL: vapor_service, 5.0, 281a70, Swift Package
07:26:48.005   FAIL: vapor_service, 4.2, 281a70, Swift Package
07:26:48.005   FAIL: vapor_template-kit, 5.1, 51405c, Swift Package
07:26:48.005   FAIL: vapor_url-encoded-form, 5.1, 82d8d6, Swift Package
07:26:48.005   FAIL: vapor_url-encoded-form, 5.0, cbfe7e, Swift Package
07:26:48.005   FAIL: vapor_url-encoded-form, 4.2, cbfe7e, Swift Package
07:26:48.005   FAIL: Nimble, 5.1, eea584, Swift Package
07:26:48.005   FAIL: swift-collections-benchmark, 5.3, 492976, Swift Package
07:26:48.005   FAIL: mqtt-nio, 5.1, 17794a, Swift Package
```

**Comment by justice-adams-apple** [comment]
@shahmishal I think we can close this. This was done with 
https://github.com/apple/swift-source-compat-suite/pull/725

**Pull request closed without merging**
