### PR TITLE
[wip] Add KSR app

### PR DESCRIPTION
**Pull request by justinswart**
This adds the main Kickstarter app to test against Swift 4.2.

This is currently failing locally but I am not receiving any useful errors from the fail log, I was hoping we could run it on CI to see if there was anything more to go by from the error messages there.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by justinswart** [comment]
Are the submodules still failing to update?

```
20:12:33 common.ExecuteCommandFailure: ExecuteCommandFailure(command="git -C /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/kickstarter-ios-oss submodule update --init --recursive", returncode=1)
```

**Comment by clackary** [comment]
Yeah, the interesting bit can be found in the artifacts for `kickstarter-ios-oss` which can be found [here](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/388/artifact/swift-source-compat-suite/).

From the [build log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/388/artifact/swift-source-compat-suite/None_kickstarter-ios-oss-Kickstarter.xcodeproj_4.2_BuildXcodeProjectScheme_Kickstarter-iOS_generic-platform-iOS.log) itself:
```
Submodule 'Frameworks/Runes' (git://github.com/thoughtbot/Runes.git) registered for path 'Frameworks/Prelude/Frameworks/Runes'
Cloning into '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/kickstarter-ios-oss/Frameworks/Prelude/Frameworks/Runes'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused
```

**Comment by justinswart** [comment]
Ah I was sure we'd fixed that - lemme take another look.

**Comment by clackary** [comment]
No worries. I noticed in the ios-oss Makefile there are some calls to git as well as some curl commands. Maybe that's where the failing Runes clone is coming from? At that point in the build, all network activity is going to be blocked by the sandbox.

**Comment by justinswart** [comment]
Will it block the curl commands too even if they're made to https?

**Comment by clackary** [comment]
Ah, I think the current failure is because this `git://github.com/thoughtbot/Runes.git` needs to use https. This call to git should not be blocked by the sandbox because it's still in the checkout phase.

I would expect the git (and curl) calls in Makefile to fail though, because all network activity is blocked after checkout phase is complete.

**Comment by justinswart** [comment]
@clackary aah ok - then I have a feeling this might not work, we have some dependencies that are downloaded by curl unfortunately. I guess the compatibility tests will have to run on Prelude and ReactiveExtensions for now!

**Comment by clackary** [comment]
Ok. Thanks for looking into it! I'll close this for now, but please let us know if this becomes a possibility in the future.

**Pull request closed without merging**
