### PR TITLE
CryptoSwift

### PR DESCRIPTION
**Pull request by krzyzanowskim**
### Pull Request Description

CryptoSwift is a growing collection of standard and secure cryptographic algorithms implemented in Swift.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [ ] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass ./check script run

### CODE REVIEW

**Comment by tkremenek** [comment]
The license has been reviewed and I approve adding this to the compatibility suite.

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by krzyzanowskim** [comment]
Hm... I'm not sure why tests failed

```
$ xcrun xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
```

```
$ ./check CryptoSwift
** CHECK **
--- Finding CryptoSwift Swift version compatibility ---
--- Project configured to be compatible with Swift 3.1 ---
--- Checking CryptoSwift platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check succeeded ---
--- Executing build actions ---
$ /Users/marcinkrzyzanowski/Devel/swift-source-compat-suite/runner.py --swift-branch swift-3.1-branch --swiftc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects /Users/marcinkrzyzanowski/Devel/swift-source-compat-suite/projects.json --include-repos 'path == "CryptoSwift"' --include-actions 'action.startswith("Build")'
PASS: CryptoSwift, 3.1, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- CryptoSwift checked successfully against Swift 3.1 ---
```

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by lplarson** [comment]
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/44/artifact/swift-source-compat-suite/FAIL_BuildSwiftPackage_CryptoSwift.log

@krzyzanowskim The project is failing to build against Xcode 9 beta 3. Please make it compatible and update the pull request.

**Comment by lplarson** [comment]
To clarify, @_specialize is prefixed with an underline, meaning that it's not guaranteed to be source compatible. Please remove the @_specialize annotations.

**Comment by lplarson** [comment]
@krzyzanowskim Please open a new pull request if you'd still like this project added.

**Comment by krzyzanowskim** [comment]
@lplarson it's not just `@_specialize` that is different between Swift 3.1 and 3.2 (Xcode8 vs. Xcode9). The Swift Standard Library is different and conflict with the code I implemented for Swift 3.1. As a result, I decided to maintain two branches, one for Swift 3.1 and the other for Swift 3.2, until Xcode 9 release.

screen shot 2017-07-25 at 09 57 48

that said, the compatibility entry in the manifest file point to the last commit that is compatible with the Swift 3.1 release (https://github.com/krzyzanowskim/CryptoSwift/commit/85c659ac534c5f8a72eb3b72488fb941e82763bd).

```
"compatibility": {
         "3.1": {
           "commit": "85c659ac534c5f8a72eb3b72488fb941e82763bd"
         }
     },
```

maybe I misunderstood the instructions and there is an issue in the configuration then? should I add "3.2" entry and will that work? (I think I tried but it didn't recognize 3.2 version).

**Pull request closed without merging**
