### PR TITLE
Add SwiftyJSON

### PR DESCRIPTION
**Pull request by clackary**
### Pull Request Description

Adds the [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) project to the suite.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* MIT
- [x] pass `./project_precommit_check` script run
```
$ ./project_precommit_check SwiftyJSON --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating SwiftyJSON Swift version 4.2 compatibility ---
--- Project configured to be compatible with Swift 4.2 ---
--- Checking SwiftyJSON platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcodes/Xcode_10_Beta_6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check succeeded ---
--- Executing build actions ---
$ ./runner.py --swift-branch swift-4.2-branch --swiftc /Applications/Xcodes/Xcode_10_Beta_6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects projects.json --include-repos 'path == "SwiftyJSON"' --include-versions 'version == "4.2"' --include-actions 'action.startswith("Build")'
PASS: SwiftyJSON, 4.2, b93c5d, SwiftyJSON macOS, platform=macOS
PASS: SwiftyJSON, 4.2, b93c5d, SwiftyJSON iOS, generic/platform=iOS
PASS: SwiftyJSON, 4.2, b93c5d, SwiftyJSON tvOS, generic/platform=tvOS
PASS: SwiftyJSON, 4.2, b93c5d, SwiftyJSON watchOS, generic/platform=watchOS
========================================
Action Summary:
     Passed: 4
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 4
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
```

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by wongzigii** [comment]
@clackary Look Good 👍

**Comment by wongzigii** [comment]
@clackary How to update the [current list](https://swift.org/source-compatibility/#current-list-of-projects)?

**Comment by shahmishal** [comment]
@wongzigii The list is updated once a day, so you should see SwiftyJSON later today.

**Pull request merged**
