### PR TITLE
remove XFAILS for 60577

### PR DESCRIPTION
**Pull request by hyp**
This is paired up with https://github.com/apple/llvm-project/pull/5183 / https://github.com/apple/swift/pull/60733

### CODE REVIEW

**Comment by hyp** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/5183

@swift-ci please test source compatibility

**Comment by hyp** [comment]
@justice-adams-apple / @shahmishal  how do I test it with the llvm-project repo PR? The test on the Swift PR didn't seem to pick this one up.

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/5183

@swift-ci please test

**Comment by shahmishal** [comment]
@hyp You have it correct, `test` is the right trigger vs the ` test source compatibility`.

**Comment by hyp** [comment]
Please test with following pull request:
https://github.com/apple/llvm-project/pull/5183

@swift-ci please test source compatibility

**Comment by shahmishal** [comment]
> Please test with following pull request: [apple/llvm-project#5183](https://github.com/apple/llvm-project/pull/5183)
> 
> @swift-ci please test source compatibility

This need to be `@swift-ci please test` not `@swift-ci please test source compatibility`

**Comment by hyp** [comment]
@shahmishal / @justice-adams-apple could one of you approve the PR?

**Review by shahmishal — APPROVED** [review]

**Comment by hyp** [comment]
Merged llvm-project PR, merging this one.

**Pull request merged**
