### PR TITLE
Un-XFAIL SwiftLint project

### PR DESCRIPTION
**Pull request by slavapestov**
rdar://35633455 has been resolved.

### CODE REVIEW

**Comment by slavapestov** [comment]
@rudkx This look OK?

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by rudkx** [comment]
Yes, thanks!

**Comment by lplarson** [comment]
@swift-ci test

**Pull request merged**
