### PR TITLE
Add swift-algorithms

### PR DESCRIPTION
**Pull request by clackary**
### Pull Request Description

Add https://github.com/apple/swift-algorithms

### Acceptance Criteria

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* Apache License, version 2.0
- [x] pass `./project_precommit_check` script run
```
PASS: swift-algorithms, 5.2, 386460, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- swift-algorithms checked successfully against Swift 5.2 ---
```

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@natecook1000 FYI - Adding you as a maintainer here.

**Comment by shahmishal** [comment]
Can you also add tag "tags": "swiftpm"?

**Comment by clackary** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]
Thanks!

**Pull request merged**
