### PR TITLE
Add CareKit to the projects list

### PR DESCRIPTION
**Pull request by erik-apple**
### Pull Request Description
This PR adds [CareKit](https://github.com/carekit-apple/CareKit) to the source compatibility suite.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 5.2 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by erik-apple** [comment]
CI seems to be failing due to a compiler error. I've opened a bug repot here.
https://bugs.swift.org/browse/SR-12330

**Comment by erik-apple** [comment]
The bug discovered by this PR should now be fixed.
https://github.com/apple/swift/pull/30365

@clackary Could you kick off CI again?

**Comment by jckarter** [comment]
@swift-ci test

**Comment by jckarter** [comment]
@erik-apple Thank you for reporting the problem!

**Comment by erik-apple** [comment]
@jckarter Thanks for fixing it!

**Comment by clackary** [comment]
Thanks @erik-apple!

**Pull request merged**
