### PR TITLE
Updated Guitar compatibility commit in projects.json for Swift 5.0

### PR DESCRIPTION
**Pull request by ArtSabintsev**
### Pull Request Description

Changed the commit hash and version for an Xcode 10.2 / Swift 5.0 compatible version:

```json
    "compatibility": [
      {
        "version": "5.0",
        "commit": "a5e4139a7f63103f268598abce9156ad52b27cee"
      }
    ],
```

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [ ] pass `./project_precommit_check` script run

Need assistance with running the script:

```sh
$ ./project_precommit_check --earliest-compatible-swift-version 5.0 --swiftc /usr/bin/swiftc Guitar
** CHECK **
--- Validating Guitar Swift version 5.0 compatibility ---
--- Project configured to be compatible with Swift 5.0 ---
--- Checking Guitar platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
Traceback (most recent call last):
  File "./project_precommit_check", line 204, in <module>
    sys.exit(main())
  File "./project_precommit_check", line 199, in main
    config = supported_configs[platform.system()][args.earliest_compatible_swift_version]
KeyError: '5.0'
```
Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
From the [build log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/462/artifact/swift-source-compat-suite/FAIL_Guitar_5.0_BuildSwiftPackage.log), looks like there are a few availability errors.
```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Guitar/Sources/GuitarCharacter.swift:25:40: error: 'toLatin' is only available on OS X 10.11 or newer
            return (applyingTransform(.toLatin, reverse: false) ?? self).withoutAccents()
                                       ^

/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Guitar/Sources/GuitarCharacter.swift:54:21: error: 'applyingTransform(_:reverse:)' is only available on OS X 10.11 or newer
            return (applyingTransform(.stripCombiningMarks, reverse: false) ?? self)
                    ^

/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Guitar/Sources/GuitarCharacter.swift:54:40: error: 'stripCombiningMarks' is only available on OS X 10.11 or newer
            return (applyingTransform(.stripCombiningMarks, reverse: false) ?? self)
                                       ^
```

**Comment by ArtSabintsev** [comment]
Fixed the issue - thanks!

However, I have issues running the script locally.

```sh
$ ./project_precommit_check --earliest-compatible-swift-version 5.0 --swiftc /usr/bin/swiftc Guitar
** CHECK **
--- Validating Guitar Swift version 5.0 compatibility ---
--- Project configured to be compatible with Swift 5.0 ---
--- Checking Guitar platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
Traceback (most recent call last):
  File "./project_precommit_check", line 204, in <module>
    sys.exit(main())
  File "./project_precommit_check", line 199, in main
    config = supported_configs[platform.system()][args.earliest_compatible_swift_version]
KeyError: '5.0'
```

**Comment by ArtSabintsev** [comment]
Just following up.

**Comment by clackary** [comment]
@swift-ci please test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci please test

**Comment by clackary** [comment]
@swift-ci test

**Comment by ArtSabintsev** [comment]
Woot! Glad it's passed!

**Comment by clackary** [comment]
Yay! Thanks @ArtSabintsev

**Pull request merged**
