### PR TITLE
Remove tests that fail with Swift 3 expression type checking support …

### PR DESCRIPTION
**Pull request by rudkx**
…removed.

Most of these are tested with 4.x as well, and remain. I've wholesale
deleted the ones that are only tested with 3.x, but could revert those
parts of XFAIL them instead if there is a reason to do so. My thoughts
are that it's easy to replace these when we get hashes to text 4.x with.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
@clackary I can certainly XFAIL these instead, but they are definitely not going to build with 4.2 with the current hashes.

Note that `SwifterSwift` has two complete entries here, and I've deleted just the one that was testing 3.0.

**Comment by rudkx** [comment]
@clackary Let me know if you think it's worth XFAILing. If I do that I will need one or more JIRAs to reference for the tests that are XFAILed.

**Comment by clackary** [comment]
@rudkx I think it is worth XFAILing. I think there's an expectation to at least notify maintainers and give them a chance to update it before a project removed.

**Comment by rudkx** [comment]
@clackary Okay, updated to XFAIL instead (except for the project that had two entries, where I've now removed the 3.0 one).

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by rudkx** [comment]
The failures are all UPASSes for the tests that have been XFAILed but which do not fail without my compiler PR (https://github.com/apple/swift/pull/17691).

**Comment by rudkx** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/17691

@swift-ci Please test

**Comment by rudkx** [comment]
Most of these were covered by https://github.com/apple/swift-source-compat-suite/pull/210 and other PRs. I'll open a new PR for anything else that is still blocking my compiler PR.

**Pull request closed without merging**
