### PR TITLE
Migrate from Python2 to Python3

### PR DESCRIPTION
**Pull request by justice-adams-apple**
### Pull Request Description

Updated all Python scrips in the repository to support Python3 and dropped support for Python2. This included
* Fixing syntax errors throughout
* Using pythonic context managers to handle file management
* Using a proper `Enum` class for results handling
* Cleaning imports and updating shebang lines

I also took it upon myself to rename `project_future.py` -> `project.py` as we originally intended

### Acceptance Criteria
Not applicable here

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
Labelled as `WIP` for now because I need to do some manual testing quick while the CI build kicks off.

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]
LGTM! Thanks

**Comment by justice-adams-apple** [comment]
@shahmishal Will merge this today, just one question:

I saw some performance degradation when using python 3.7 to test my changes, in particular, things were just taking longer. After profiling the code I saw that the `subprocess` module was slower. This was fixed for macOS in 3.8+ 
https://docs.python.org/3.8/whatsnew/3.8.html#optimizations

And after updating to 3.9, I no longer saw an issue. The question is: Should we note on the readme that this repository is now targeting python 3.8+, just to be explicit for end-users? If so, I can update this branch quickly to include a change for the readme

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
> @shahmishal Will merge this today, just one question:
> 
> I saw some performance degradation when using python 3.7 to test my changes, in particular, things were just taking longer. After profiling the code I saw that the `subprocess` module was slower. This was fixed for macOS in 3.8+ https://docs.python.org/3.8/whatsnew/3.8.html#optimizations
> 
> And after updating to 3.9, I no longer saw an issue. The question is: Should we note on the readme that this repository is now targeting python 3.8+, just to be explicit for end-users? If so, I can update this branch quickly to include a change for the readme

Let's update the README to contain the info, it's ok to do this in new PR.

**Pull request merged**
