### PR TITLE
Add Kommander

### PR DESCRIPTION
**Pull request by alexruperez**
### Pull Request Description

[Kommander](https://github.com/intelygenz/Kommander-iOS) is a Swift library to manage the task execution in different threads. Through the definition a simple but powerful concept, Kommand.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass ./check script run

---
This change is [Reviewable](https://reviewable.io/reviews/apple/swift-source-compat-suite/27)

### CODE REVIEW

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by alexruperez** [comment]
@tkremenek in order to speed up the process, I have deleted NetClient from this pull request and when I investigate why it breaks the CI, I will upload it in another pull request, for now Kommander is working. :) @swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by lplarson** [comment]
Thanks!

**Pull request merged**
