### PR TITLE
Add SwiftGraph Against Swift 3.1

### PR DESCRIPTION
**Pull request by davecom**
### Pull Request Description

SwiftGraph is a graph data structure and related algorithms. It wasn't clear to me from the README if you're yet accepting 3.1 pull requests because it said the 3.0s were "examples." Specifically, I mean this section:

```
After adding a new project to the index, ensure it builds successfully at the pinned commits against the specified versions of Swift. In the examples, the commits are specified as being compatible with Swift 3.0, which is included in Xcode 8.0.
```

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [X] be an *Xcode* or *swift package manager* project
- [X] support building on either Linux or macOS
- [X] target Linux, macOS, or iOS/tvOS/watchOS device
- [X] be contained in a publicly accessible git repository
- [ ] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [X] have maintainers who will commit to resolve issues in a timely manner
- [X] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [X] add value not already included in the suite
- [X] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [X] pass ./check script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by lplarson** [comment]
To clarify, this project won't build against 3.0? I'd prefer if we set the version to the earliest version of Swift still supported (bottoming out at 3.0), but we will accept Swift 3.1 projects.

**Comment by slavapestov** [comment]
We definitely do want projects that require Swift 3.1 too - Swift 3.1 is a superset of Swift 3.0 (mostly, except for a handful of unfortunate quirks).

(Once Swift 4 is out we will accept projects that depend on that too, but for now we don't want anything that only builds against master and not 3.1 -- the "Swift 4" language isn't finalized yet.)

**Comment by slavapestov** [comment]
@lplarson I wonder if we should look into splitting up packages.json into one file per project. Otherwise we will be constantly resolving merge conflicts

**Comment by lplarson** [comment]
@slavapestov Yeah, they aren't merging very cleanly. I'll look into it.

**Comment by davecom** [comment]
Thanks for the replies. It does support Swift 3.0 - I didn't have a version of it installed to test against, so I tested against 3.1 and submitted that here. It would be great to have a separate `.json` file for each project. I can install an old version of Xcode and test against 3.0 if you would like me to do that and update the pull request.

**Comment by lplarson** [comment]
@swift-ci test

**Pull request merged**
