### PR TITLE
add CoreStore

### PR DESCRIPTION
**Pull request by JohnEstropia**
### Pull Request Description

Replace with a description of this pull request. Instructions for adding
projects are available in the README.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass ./check script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by JohnEstropia** [comment]
@swift-ci Please test source compatibility

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by JohnEstropia** [comment]
@tkremenek Thanks. I'm not sure where the check failed as running `./check CoreStore` passes locally for me. Can this be caused by the target supporting only Swift 3.1 and not 3.0? (I was under the impression that the`compatibility` json key specifies the Swift version though)

**Comment by tkremenek** [comment]
@lplarson I can't tell where the actual failure is.  Looks like everything is passing.

**Comment by lplarson** [comment]
Swift is crashing. I'll file a Jira.

```
0  swift                    0x000000010d7d7e68 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x000000010d7d8486 SignalHandler(int) + 342
2  libsystem_platform.dylib 0x00007fffcac3bbba _sigtramp + 26
3  libsystem_platform.dylib 0x000000011726b291 _sigtramp + 1281554161
4  libsystem_c.dylib        0x00007fffcaac2420 abort + 129
5  swift                    0x000000010b635f8f swift::ModuleFile::readConformance(llvm::BitstreamCursor&, swift::GenericEnvironment*) + 1823
6  swift                    0x000000010b636691 swift::ModuleFile::readNormalConformance(llvm::PointerEmbeddedInt<unsigned int, 31>) + 801
7  swift                    0x000000010b635cf8 swift::ModuleFile::readConformance(llvm::BitstreamCursor&, swift::GenericEnvironment*) + 1160
8  swift                    0x000000010b63dd6d swift::ModuleFile::loadAllConformances(swift::Decl const*, unsigned long long, llvm::SmallVectorImpl<swift::ProtocolConformance*>&) + 221
9  swift                    0x000000010b99c9cc swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 2124
10 swift                    0x000000010b99c2a7 swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 295
11 swift                    0x000000010b99e8a5 swift::ConformanceLookupTable::lookupConformance(swift::ModuleDecl*, swift::NominalTypeDecl*, swift::ProtocolDecl*, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ProtocolConformance*>&) + 53
12 swift                    0x000000010b635aab swift::ModuleFile::readConformance(llvm::BitstreamCursor&, swift::GenericEnvironment*) + 571
13 swift                    0x000000010b636691 swift::ModuleFile::readNormalConformance(llvm::PointerEmbeddedInt<unsigned int, 31>) + 801
14 swift                    0x000000010b635cf8 swift::ModuleFile::readConformance(llvm::BitstreamCursor&, swift::GenericEnvironment*) + 1160
15 swift                    0x000000010b63dd6d swift::ModuleFile::loadAllConformances(swift::Decl const*, unsigned long long, llvm::SmallVectorImpl<swift::ProtocolConformance*>&) + 221
16 swift                    0x000000010b99c9cc swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 2124
17 swift                    0x000000010b99c2a7 swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 295
18 swift                    0x000000010b99e8a5 swift::ConformanceLookupTable::lookupConformance(swift::ModuleDecl*, swift::NominalTypeDecl*, swift::ProtocolDecl*, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ProtocolConformance*>&) + 53
19 swift                    0x000000010b9f4ba1 swift::ModuleDecl::lookupConformance(swift::Type, swift::ProtocolDecl*, swift::LazyResolver*) + 785
20 swift                    0x000000010b6f2e0e swift::ClangImporter::Implementation::finishProtocolConformance(swift::NormalProtocolConformance*) + 942
21 swift                    0x000000010b6f2997 swift::ClangImporter::Implementation::finishPendingActions() + 39
22 swift                    0x000000010b6f3320 swift::ClangImporter::Implementation::importDeclAndCacheImpl(clang::NamedDecl const*, swift::importer::ImportNameVersion, bool) + 896
23 swift                    0x000000010b6da8c0 swift::ClangImporter::Implementation::lookupValue(swift::SwiftLookupTable&, swift::DeclName, swift::VisibleDeclConsumer&) + 384
24 swift                    0x000000010b6da71f swift::ClangModuleUnit::lookupValue(llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, swift::NLKind, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 431
25 swift                    0x000000010b9f3d5a swift::ModuleDecl::lookupValue(llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, swift::NLKind, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 90
26 swift                    0x000000010b9fe8ca void lookupInModule<llvm::SmallSet<swift::CanType, 4u, (anonymous namespace)::SortCanType>, swift::namelookup::lookupInModule(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::NLKind, swift::namelookup::ResolutionKind, swift::LazyResolver*, swift::DeclContext const*, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >)::$_0>(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::namelookup::ResolutionKind, bool, swift::LazyResolver*, llvm::SmallDenseMap<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*>, llvm::TinyPtrVector<swift::ValueDecl*>, 32u, llvm::DenseMapInfo<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >, llvm::detail::DenseMapPair<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*>, llvm::TinyPtrVector<swift::ValueDecl*> > >&, swift::DeclContext const*, bool, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >, swift::namelookup::lookupInModule(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::NLKind, swift::namelookup::ResolutionKind, swift::LazyResolver*, swift::DeclContext const*, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >)::$_0) + 346
27 swift                    0x000000010b9fecec void lookupInModule<llvm::SmallSet<swift::CanType, 4u, (anonymous namespace)::SortCanType>, swift::namelookup::lookupInModule(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::NLKind, swift::namelookup::ResolutionKind, swift::LazyResolver*, swift::DeclContext const*, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >)::$_0>(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::namelookup::ResolutionKind, bool, swift::LazyResolver*, llvm::SmallDenseMap<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*>, llvm::TinyPtrVector<swift::ValueDecl*>, 32u, llvm::DenseMapInfo<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >, llvm::detail::DenseMapPair<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*>, llvm::TinyPtrVector<swift::ValueDecl*> > >&, swift::DeclContext const*, bool, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >, swift::namelookup::lookupInModule(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::NLKind, swift::namelookup::ResolutionKind, swift::LazyResolver*, swift::DeclContext const*, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >)::$_0) + 1404
28 swift                    0x000000010b9fe73e swift::namelookup::lookupInModule(swift::ModuleDecl*, llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::DeclName, llvm::SmallVectorImpl<swift::ValueDecl*>&, swift::NLKind, swift::namelookup::ResolutionKind, swift::LazyResolver*, swift::DeclContext const*, llvm::ArrayRef<std::__1::pair<llvm::ArrayRef<std::__1::pair<swift::Identifier, swift::SourceLoc> >, swift::ModuleDecl*> >) + 1278
29 swift                    0x000000010ba04df0 swift::DeclContext::lookupQualified(swift::Type, swift::DeclName, swift::NLOptions, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 1136
30 swift                    0x000000010b637ae8 swift::ModuleFile::resolveCrossReference(swift::ModuleDecl*, unsigned int) + 760
31 swift                    0x000000010b6311be swift::ModuleFile::getDeclChecked(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 12398
32 swift                    0x000000010b63b4eb swift::ModuleFile::getTypeChecked(llvm::PointerEmbeddedInt<unsigned int, 31>) + 3819
33 swift                    0x000000010b63158a swift::ModuleFile::getDeclChecked(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 13370
34 swift                    0x000000010b62d59e swift::ModuleFile::getDecl(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 78
35 swift                    0x000000010b65c49b swift::ModuleFile::getTopLevelDecls(llvm::SmallVectorImpl<swift::Decl*>&) + 2043
36 swift                    0x000000010b9f460f swift::ModuleDecl::getTopLevelDecls(llvm::SmallVectorImpl<swift::Decl*>&) const + 63
37 swift                    0x000000010b2a009f swift::ClassHierarchyAnalysis::init() + 79
38 swift                    0x000000010b295ee1 swift::createClassHierarchyAnalysis(swift::SILModule*) + 129
39 swift                    0x000000010b3417cb swift::SILPassManager::SILPassManager(swift::SILModule*, llvm::StringRef) + 427
40 swift                    0x000000010b34978b swift::runSILDiagnosticPasses(swift::SILModule&) + 123
41 swift                    0x000000010ac38ece performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 7870
42 swift                    0x000000010ac3616d swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2621
43 swift                    0x000000010abfce8a main + 2346
44 libdyld.dylib            0x00007fffcaa2e255 start + 1

1.	While reading from /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/CoreStore/build/Build/Intermediates/CoreStore.build/Release-iphoneos/CoreStore iOS.build/Objects-normal/arm64/CoreDataNativeType~partial.swiftmodule
2.	While deserializing extension of '<null>' (ExtensionDecl #5) in 'CoreStore'
3.	While deserializing decl #15 (XREF) in 'CoreStore'
4.	Cross-reference to module 'Foundation'
	... NSData
5.	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSManagedObjectModel.h:16:8: importing 'NSData'
6.	While loading conformances for extension of NSData in module 'CoreStore'
7.	While reading conformance for type 'NSData'
8.	While ... to 'CoreStoreImportableAttributeType' in module 'CoreStore'
9.	While cross-referencing conformance for 'NSData' in module 'Foundation'
10.	While ... to 'CoreStoreQueryableAttributeType' in module 'CoreStore'
11.	While loading conformances for extension of NSData in module 'CoreStore'
12.	While reading conformance for type 'NSData'
13.	While ... to 'CoreStoreQueryableAttributeType' in module 'CoreStore'
14.	While cross-referencing conformance for 'NSData' in module 'Foundation'
15.	While ... to 'CoreDataNativeType' in module 'CoreStore'
16.	If you're seeing a crash here, check that your SDK and dependencies are at least as new as the versions used to build 'CoreStore'

<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: merge-module command failed due to signal 6 (use -v to see invocation)
** BUILD FAILED **

**Comment by lplarson** [comment]
Looks good. Thanks!

**Comment by JohnEstropia** [comment]
@lplarson Thanks!

**Pull request merged**
