### PR TITLE
Add 4.0 compatibility to SwifterSwift

### PR DESCRIPTION
**Pull request by omaralbeik**
### Pull Request Description

Add Swift 4.0 compatibility commit to SwifterSwift

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by lplarson** [comment]
@swift-ci test

**Comment by lplarson** [comment]
xcodebuild: error: The workspace named "SwifterSwift" does not contain a scheme named "SwifterSwift iOS". The "-list" option can be used to find the names of the schemes in the workspace.

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Ah, looks like this is passing on version 4.0, but now fails for version 3.0 because the scheme at that point looked like "SwifterSwift iOS". Different scheme names for the same project are not supported, but we can work around this by making a 'new' project entry in projects.json with the 4.0 commit and schemes.

It should work if you duplicate the existing SwifterSwift project entry into a second one, and then update it with your 4.0 version/commit and the actions with the correct scheme names. The important thing is your 3.0 actions should have a space in the scheme name, and the 4.0 actions should use a dash.

The current configuration can stay as is, but the new one should look something like this...
<pre>
  {
    "repository": "Git",
    "url": "https://github.com/SwifterSwift/SwifterSwift.git",
    "path": "SwifterSwift",
    "branch": "master",
    "maintainer": "omaralbeik@gmail.com",
    "compatibility": [
      {
        <b>"version": "4.0",
        "commit": "21316259f00fe1254d985e89dad6a50de08f551f"</b>
      }
    ],
    "platforms": [
      "Darwin"
    ],
    "actions": [
      {
        "action": "BuildXcodeWorkspaceScheme",
        "workspace": "SwifterSwift.xcworkspace",
        <b>"scheme": "SwifterSwift-iOS",</b>
        "destination": "generic/platform=iOS",
        "configuration": "Release"
      },
...
</pre>

**Comment by clackary** [comment]
Hi @omaralbeik, would you be able to make the changes I outlined above when you get the chance?

**Comment by omaralbeik** [comment]
Hi @clackary, sorry for my late response 😅, I made the changes as outlined above.

**Comment by clackary** [comment]
No worries! Thanks for making the changes.

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Looks good, thanks!

**Pull request merged**
