### PR TITLE
[WIP] [Prototype] Parallelize project builds

### PR DESCRIPTION
**Pull request by justice-adams-apple**
### Pull Request Description

WIP PR to gather timing metrics. Not in any way ready to merge or review

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
I would recommend cherry-picking the commits from `PR-py2-to-3` branch, and set the targeted branch to main. Otherwise, the pull request system will not work as expected.

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
Based off the last CI timings of this prototype: 
* Build time: **99 minutes**
* Source compat project suite time: **56 minutes**

Averaging the previous 3 runs on master and _assuming the build time was the same_ (Don't have timings), the previous source compat project suite time was: ~**200 minutes**

Going to work on cleaning this up as the improvement in project build times is worthwhile

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
This prototype is finished.

Going to separate this into two PR's:
* Converting un-pickle-able factory pattern into abstract class
* Adding multiprocessing to the ProjectListBuilder

Will keep this open until those are in

**Comment by justice-adams-apple** [comment]
Became clear that the factory pattern was the way to do things, as it keeps the code less complicated, allows for easier extension into new BuilderObjects, and doesn't require a bunch of nasty logic to verify instance variables that are set outside of constructors. 

In any case, closing this PR in favor of the new implementation. The final PR can be found here: #687

**Pull request closed without merging**
