### PR TITLE
Un-XFAIL Vapor

### PR DESCRIPTION
**Pull request by dabrahams**
Goes with https://github.com/apple/swift/pull/9847

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by dabrahams** [comment]
@shahmishal This won't pass tests on its own; it needs to be tested with apple/swift#9847.

**Comment by shahmishal** [comment]
apple/swift#9847

@swift-ci test

**Comment by dabrahams** [comment]
That's redundant since I triggered it from the other PR, neh?

**Comment by lplarson** [comment]
You need to remove the comma at the end of:

"configuration": "release",

**Comment by dabrahams** [comment]
apple/swift#9847

@swift-ci test

**Comment by dabrahams** [comment]
apple/swift#9847

@swift-ci test

**Comment by lplarson** [comment]
Looks good! Thanks.

**Pull request merged**
