### PR TITLE
Update for Doggie 6.7.0

### PR DESCRIPTION
**Pull request by SusanDoggie**
### Pull Request Description

Update for Doggie 6.7.0

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@SusanDoggie seeing
```
Doggie/Sources/DoggieGPU/CoreImage/ShaderLoader.swift:39:96: error: type 'Bundle' has no member 'module'
        guard let library = try? libraries[device] ?? device.makeDefaultLibrary(bundle: Bundle.module) else { return nil }
                                                                                        ~~~~~~ ^~~~~~
Doggie/Sources/DoggieGPU/GPContext/MeshGradientKernel.swift:89:79: error: type 'Bundle' has no member 'module'
            guard let library = try? device.makeDefaultLibrary(bundle: Bundle.module) else { return nil }
                                                                       ~~~~~~ ^~~~~~
```
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/122/artifact/swift-source-compat-suite/FAIL_Doggie_5.7_BuildSwiftPackage.log

**Comment by SusanDoggie** [comment]
> @SusanDoggie seeing
> 
> ```
> Doggie/Sources/DoggieGPU/CoreImage/ShaderLoader.swift:39:96: error: type 'Bundle' has no member 'module'
>         guard let library = try? libraries[device] ?? device.makeDefaultLibrary(bundle: Bundle.module) else { return nil }
>                                                                                         ~~~~~~ ^~~~~~
> Doggie/Sources/DoggieGPU/GPContext/MeshGradientKernel.swift:89:79: error: type 'Bundle' has no member 'module'
>             guard let library = try? device.makeDefaultLibrary(bundle: Bundle.module) else { return nil }
>                                                                        ~~~~~~ ^~~~~~
> ```
> 
> https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/122/artifact/swift-source-compat-suite/FAIL_Doggie_5.7_BuildSwiftPackage.log

I have updated the xfail

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Review by justice-adams-apple — APPROVED** [review]

**Pull request merged**
