### PR TITLE
Update projects.json

### PR DESCRIPTION
**Pull request by SusanDoggie**
update xfails

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Review by justice-adams-apple — APPROVED** [review]
LGTM. Thanks @SusanDoggie

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
Hi @SusanDoggie 👋 , unfortunately a new build issue has been uncovered.  I went ahead and created a github issue:
https://github.com/apple/swift/issues/60627

The good news is your project helped us uncover a compiler crash 👍 . The bad news is you'll need to update this branch projects.json to include an xfail with the newly created git issue.  Once that's in we can go ahead and merge this guy. I'll go ahead and remove said xfail in the future once the compiler is fixed and the build passes

**Comment by SusanDoggie** [comment]
Hi @justice-adams-apple 

I have update the package.json. please check.

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Pull request merged**
