### PR TITLE
[4.2][4.0] Update URBNJSONDecodableSPM from Swift 3.1

### PR DESCRIPTION
**Pull request by shahmishal**
```
PASS: URBNJSONDecodableSPM, 4.0, 6dc998, Swift Package
PASS: URBNJSONDecodableSPM, 4.2, 6dc998, Swift Package
```

### CODE REVIEW

**Comment by shahmishal** [comment]
Failure is due to SwiftPM: 

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/URBNJSONDecodableSPM: error: package at '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/URBNJSONDecodableSPM' is using Swift tools version 3.1.0 which is no longer supported; use 4.0.0 or newer instead
```

**Comment by shahmishal** [comment]
We can merge this once this issue has been resolved -- https://forums.swift.org/t/rfc-tools-version-with-version-specific-manifests/18224

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by clackary** [comment]
It looks like this project hasn't had any updates for a while. I've reached out to the maintainer a few times via email, but haven't heard anything back. Closing this for now.

**Pull request closed without merging**
