### PR TITLE
XFAIL JSQDataSourcesKit

### PR DESCRIPTION
**Pull request by aschwaighofer**
SR-6484

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by lplarson** [comment]
You'll need to remove the trailing comma:

"master": "https://bugs.swift.org/browse/SR-6484",

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by lplarson** [comment]
LGTM

**Pull request merged**
