### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
### Pull Request Description

Some minimal, "safe" changes to make the code syntax compatible with both Python 2 and Python 3.
* Run __futurize --stage1__ http://python-future.org/futurize_cheatsheet.html

Python 3 syntax compatibility does __not__ mean that the port is complete.  More work may be required to complete the port to Python 3.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [X] be an *Xcode* or *swift package manager* project
- [X] support building on either Linux or macOS
- [X] target Linux, macOS, or iOS/tvOS/watchOS device
- [X] be contained in a publicly accessible git repository
- [X] maintain a project branch that builds against Swift 3.0 compatibility mode
      or Swift 4.0 and passes any unit tests
- [X] have maintainers who will commit to resolve issues in a timely manner
- [X] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [X] add value not already included in the suite
- [X] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [X] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by cclauss** [comment]
@swift-ci please test

**Comment by clackary** [comment]
@swift-ci please test

**Comment by Rostepher** [comment]
Thanks for getting this started @cclauss! While modernizing Python 2 source to be Python 3 compatible is a good idea, it's unlikely that Swift nor the source compatibility suite will be pure Python 3 projects anytime soon. We primarily support Python 2.7.10 and up as that ships with macOS by default.

**Comment by clackary** [comment]
Thanks @Rostepher and @cclauss, going to go ahead and merge this.

**Comment by cclauss** [comment]
Some day soon Apple will need to follow the Linux distros and ship Python 3 as the default.

Given https://pythonclock.org now is the time to start getting ready for that day.

**Pull request merged**
