### PR TITLE
NonEmpty passes on swift-5.0-branch too now

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
```
13:33:16     obj, end = self.scan_once(s, idx)
13:33:16 ValueError: Expecting property name: line 1336 column 7 (char 34689)
13:33:16 Traceback (most recent call last):
13:33:16   File "./swift-source-compat-suite/run", line 277, in <module>
13:33:16     sys.exit(main())
13:33:16   File "./swift-source-compat-suite/run", line 44, in main
13:33:16     execute_runner(workspace, args)
13:33:16   File "./swift-source-compat-suite/run", line 185, in execute_runner
13:33:16     common.check_execute(runner_command, timeout=9999999)
```

@shahmishal any ideas?

**Comment by shahmishal** [comment]
@slavapestov Looks like it failed due to a comma.

```
"configuration": "Release",
```

**Comment by xedin** [comment]
I was about to say that too :)

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
Oops!

**Comment by slavapestov** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Merged to unblock 5.0 branch CI jobs

**Pull request merged**
