### PR TITLE
Update the llvm-project branch for main config

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by justice-adams-apple — APPROVED** [review]
LGTM

**Comment by shahmishal** [comment]
```
========================================
Failures:
  FAIL: line-sdk-ios-swift, 5.0, d8bb2b, LineSDK, generic/platform=iOS
  FAIL: line-sdk-ios-swift, 4.2, d8bb2b, LineSDK, generic/platform=iOS
========================================
```

**Comment by justice-adams-apple** [comment]
@shahmishal should we xfail that project for the time being to get this in? I think all source compat runs which build the compiler will fail until this lands due to using an outdated llvm branch

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Pull request merged**
