### PR TITLE
Update Tagged

### PR DESCRIPTION
**Pull request by stephencelis**
This fixes Tagged :)

### CODE REVIEW

**Comment by airspeedswift** [comment]
@swift-ci please test source compatibility

**Comment by clackary** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
19:13:25 ========================================
19:13:25 Failures:
19:13:25   FAIL: Tagged, 5.0, 588090, Tagged-Package, generic/platform=watchOS
19:13:25   FAIL: Tagged, 5.0, 588090, Tagged-Package, generic/platform=tvOS
19:13:25   FAIL: Tagged, 5.0, 588090, Tagged-Package, generic/platform=iOS
19:13:25   FAIL: Tagged, 5.0, 588090, Tagged-Package, generic/platform=macOS
19:13:25 ========================================
```
Log:

```
$ chflags -R nouchg /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged
$ git -C /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged clean -ffdx
Removing build/
$ git -C /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged rev-parse HEAD
current_sha: 588090cd4f30ca323567811ac45182d93aded833
configured_sha: 588090cd4f30ca323567811ac45182d93aded833
current_sha == configured_sha
$ git -C /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged checkout -f 588090cd4f30ca323567811ac45182d93aded833
HEAD is now at 588090c Update podspecs to point to 0.4.0.
$ perl -i -00ne 'print unless /Begin PBXResourcesBuildPhase/' /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/Tagged.xcodeproj/project.pbxproj
$ sandbox-exec -f /Users/buildnode/jenkins/workspace-private/swift-source-compat-suite-sandbox/sandbox_xcodebuild.sb xcodebuild clean build -workspace /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/Tagged.xcworkspace -scheme Tagged-Package -destination generic/platform=iOS -derivedDataPath /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO ENTITLEMENTS_REQUIRED=NO ENABLE_BITCODE=NO INDEX_ENABLE_DATA_STORE=NO GCC_TREAT_WARNINGS_AS_ERRORS=NO SWIFT_TREAT_WARNINGS_AS_ERRORS=NO SWIFT_EXEC=/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/bin/swiftc -configuration Release SWIFT_VERSION=5 'OTHER_SWIFT_FLAGS=$(OTHER_SWIFT_FLAGS) -swift-version 5'
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/build

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ENABLE_BITCODE = NO
    ENTITLEMENTS_REQUIRED = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = NO
    INDEX_ENABLE_DATA_STORE = NO
    OTHER_SWIFT_FLAGS = $(OTHER_SWIFT_FLAGS) -swift-version 5
    SWIFT_EXEC = /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/bin/swiftc
    SWIFT_TREAT_WARNINGS_AS_ERRORS = NO
    SWIFT_VERSION = 5

--- xcodebuild: WARNING: Unable to open project file '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/Tagged.playground' in workspace '/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/Tagged/Tagged.xcworkspace'.
xcodebuild: error: The workspace named "Tagged" does not contain a scheme named "Tagged-Package". The "-list" option can be used to find the names of the schemes in the workspace.
```

cc/ @stephencelis

**Comment by clackary** [comment]
Updated Tagged configuration in #358.

**Pull request closed without merging**
