### PR TITLE
XFAIL Kitura; it's (indirectly) referencing underscored protocols.

### PR DESCRIPTION
**Pull request by jrose-apple**
rdar://problem/34812868

### CODE REVIEW

**Comment by airspeedswift** [comment]
Thanks @jrose-apple, I guess I should run the compat suite even on stuff I know allowable breakage next time...

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
@swift-ci Please test source compatibility

**Comment by jrose-apple** [comment]
Force-merging to clear up the bots.

**Pull request merged**
