### PR TITLE
XFAIL MovieSwift

### PR DESCRIPTION
**Pull request by aschwaighofer**
rdar://62928937

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test

**Comment by Dimillian** [comment]
Should that be added to https://github.com/apple/swift-source-compat-suite/pull/424 too ?

**Comment by aschwaighofer** [comment]
The failure this tried to address was fixed by https://github.com/apple/swift/pull/31639

**Pull request closed without merging**
