### PR TITLE
Bump `swift-argument-parser` to 1.1.4

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This PR is accompanied by https://github.com/apple/swift/pull/59009 https://github.com/apple/swift-driver/pull/1218 https://github.com/apple/swift-package-manager/pull/5884 https://github.com/apple/sourcekit-lsp/pull/673 and should be merged synchronously with those.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Review by justice-adams-apple — APPROVED** [review]
LGTM, I'll leave the merge to you whenever the others are ready

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Pull request merged**
