### PR TITLE
add a SwiftLint commit to test it on Swift 3.1

### PR DESCRIPTION
**Pull request by jpsim**
as requested in https://github.com/apple/swift-source-compat-suite/pull/3#issuecomment-297223329

### CODE REVIEW

**Comment by lplarson** [comment]
Thanks. I'll merge this after I fix a couple of bugs around having multiple Swift version commits.

**Comment by jpsim** [comment]
rebased

**Comment by tkremenek** [comment]
@swift-ci test

**Comment by jpsim** [comment]
Thanks for running that test! Is there somewhere in Jenkins where I can see the log for the failure? All I can find is this:

```
common.ExecuteCommandFailure: ExecuteCommandFailure(command="./runner.py --swiftc /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/bin/swiftc --projects projects.json --swift-version 3 --include-actions 'action.startswith("Build")' --swift-branch master --sandbox-profile-xcodebuild ../../../workspace-private/swift-source-compat-suite-sandbox/sandbox_xcodebuild.sb --sandbox-profile-package ../../../workspace-private/swift-source-compat-suite-sandbox/sandbox_package.sb", returncode=1)
Build step 'Execute shell' marked build as failure
```

Which doesn't have the `swiftc` log output.

The commit I added here seems to work when I perform this local check:

```
$ git diff
diff --git a/projects.json b/projects.json
index 7701522..7e8cc75 100644
--- a/projects.json
+++ b/projects.json
@@ -1556,9 +1556,6 @@
     "path": "SwiftLint",
     "branch": "master",
     "compatibility": {
-      "3.0": {
-        "commit": "e4fa18df06ddbcc730dd2c08a1c0c42aa531ae0c"
-      },
       "3.1": {
         "commit": "ab664127d5d32d9ddd655b2cc313abe528a66a42"
       }
$ swift --version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
$ ./check SwiftLint
** CHECK **
--- Finding SwiftLint Swift version compatibility ---
--- Project configured to be compatible with Swift 3.1 ---
--- Checking SwiftLint platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcode-8.3.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check succeeded ---
--- Executing build actions ---
$ /Users/jp/Projects/swift-source-compat-suite/runner.py --swift-branch swift-3.1-branch --swiftc /Applications/Xcode-8.3.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects /Users/jp/Projects/swift-source-compat-suite/projects.json --include-repos 'path == "SwiftLint"' --include-actions 'action.startswith("Build")'
PASS: SwiftLint, 3.1, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- SwiftLint checked successfully against Swift 3.1 ---
```

So maybe an `XFAIL` needs to be added since from the logs @swift-ci appears to be running a Swift 4 compiler in `--swift-version 3` mode, but I can't add the appropriate XFAIL if I can't reproduce the failure or see it in Jenkins.

**Comment by lplarson** [comment]
A link to the build artifacts is at the bottom of the log: https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/9//artifact/swift-source-compat-suite/

There you can see the output split by action.

**Comment by jpsim** [comment]
Thanks for sharing that! The only `FAIL_` file in there is for the existing Swift 3.0 commit, which is marked as `xfail` due to [SR-4696](https://bugs.swift.org/browse/SR-4696). See [FAIL_BuildSwiftPackage_SwiftLint.log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/9//artifact/swift-source-compat-suite/FAIL_BuildSwiftPackage_SwiftLint.log) from the artifacts.

**Comment by lplarson** [comment]
Thanks!

**Pull request merged**
