### PR TITLE
Update version of Doggie

### PR DESCRIPTION
**Pull request by SusanDoggie**
Update version of Doggie

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by SusanDoggie** [comment]
Is the failure not caused by me?

**Comment by shahmishal** [comment]
This project is marked XFailed, is that still expected with new SHA?
```
 "xfail": [
            {
                "issue": "https://bugs.swift.org/browse/SR-12736",
                "platform": "Linux",
                "compatibility": "5.3",
                "branch": ["main", "release/5.5", "release/5.4"]
            },
            {
                "issue": "https://bugs.swift.org/browse/SR-14580",
                "compatibility": "5.3",
                "branch": ["main", "release/5.5"]
            },
            {
                "issue": "https://bugs.swift.org/browse/SR-14659",
                "compatibility": "5.3",
                "branch": ["release/5.4"]
            }
        ]
```

Here is the failure: 

```
error: compile command failed due to signal 6 (use -v to see invocation)Right hand side does not have a canonical parent: same_type: τ_0_0.Model.Float16Components τ_1_0.Model.Float16Components.Model.Float16Components
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/bin/swift-frontend -frontend -c -filelist /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryDirectory.4RA14y/sources-1 -supplementary-output-file-map /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryDirectory.4RA14y/supplementaryOutputs-1 -target x86_64-apple-macosx10.12 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -I /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release -I /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -module-cache-path /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release/ModuleCache -swift-version 5 -O -D SWIFT_PACKAGE -new-driver-path /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/bin/swift-driver -resource-dir /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/build/compat_macos/install/toolchain/usr/lib/swift -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/libjpeg/Sources/include/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/libjpeg/Sources/include -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release/libwebp.build/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/libwebp/dependencies/libwebp/src/webp -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release/brotli.build/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/brotli/dependencies/brotli/c/include -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release/CFloat16.build/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/Float16/Sources/CFloat16/include -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/swift-numerics/Sources/_NumericsShims/include/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/checkouts/swift-numerics/Sources/_NumericsShims/include -Xcc -fmodule-map-file=/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/.build/x86_64-apple-macosx/release/zlib_c.build/module.modulemap -Xcc -I -Xcc /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/Sources/zlib_c/include -module-name DoggieGraphics -target-sdk-version 12.0.0 -parse-as-library -num-threads 24 -output-filelist /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryDirectory.4RA14y/outputs-1
1.	Apple Swift version 5.6-dev (LLVM a29f52d415422f3, Swift 6766824d5140d35)
2.	Compiling with the current language version
3.	Contents of /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/TemporaryDirectory.4RA14y/sources-1:
---
<removed list of files>
---
4.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/Sources/DoggieGraphics/ApplePlatform/Graphic/CGContext.swift")
5.	While evaluating request TypeCheckFunctionBodyRequest(DoggieGraphics.(file).ColorSpace extension.shading_function(colorSpace:stops:)@/Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Doggie/Sources/DoggieGraphics/ApplePlatform/Graphic/CGContext.swift:165:10)
...
```

**Comment by shahmishal** [comment]
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/784/artifact/swift-source-compat-suite/XFAIL_Doggie_5.3_BuildSwiftPackage.log

**Comment by SusanDoggie** [comment]
It’s look like SR-12736 or SR-14659

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
