### PR TITLE
Use update-checkout to pull swift dependencies

### PR DESCRIPTION
**Pull request by justice-adams-apple**
### Pull Request Description
* Use update-checkout to reduce work related to keeping swift dependencies up to date for compiler builds

This will allow us to have 1 location to update when dependency updates are needed, eliminating the need for PR's such as #799 or #796

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
```
========================================
Failures:
  FAIL: swift-distributed-actors, 5.7, e024c1, Swift Package
========================================
```

This is unrelated, will open a PR for this xfail separately (https://github.com/apple/swift-distributed-actors/issues/1113)

**Comment by ktoso** [comment]
Rather than xfailing this consistently can we fix the build runner to allow passing -enable-testing? This has been a consistent painpoint for projects that didn't adopt "SPI" style

**Comment by ktoso** [comment]
Awesome, passed! Thank you @justice-adams-apple !

**Review by ktoso — APPROVED** [review]

**Comment by justice-adams-apple** [comment]
@ahoppen Wanted to run this by you before merging since it changes the `run_sk_stress_test` logic

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
