### PR TITLE
Support substituting the values of fields in the current project's action and repo into runner.py's --added-swift-args

### PR DESCRIPTION
**Pull request by nathawes**
### Pull Request Description
This enables having a per-project index store, for example, via:
--added-swift-args="-index-store-path /tmp/{path}/{branch}/index-store"
which in the swift invocations becomes:
-index-store-path /tmp/Alamofire/master/index-store
-index-store-path /tmp/SnapKit/develop/index-store
etc.

### CODE REVIEW

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@nathawes Updating Xcode on CI.

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
@swift-ci please test

**Pull request merged**
