### PR TITLE
Added Guitar

### PR DESCRIPTION
**Pull request by ArtSabintsev**
### Pull Request Description

Guitar adds common string manipulation functions, including common regular expression capabilities, that are needed in both mobile and server-side development, but are missing in Swift's Standard Library.
### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass ./check script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
@swift-ci Please test source compatibility

**Comment by lplarson** [comment]
Hi @ArtSabintsev, we currently support pull request testing the Swift repository against the source compatibility suite. We're looking into adding pull request testing of the Swift source compatibility suite itself, but it's currently unsupported.

**Comment by lplarson** [comment]
Please use the ./check script locally to check projects until we add ./check script pull request testing.

**Comment by ArtSabintsev** [comment]
@lplarson 

I'm not sure if I'm doing something wrong, but:

```
$ sudo xcode-select -s /Applications/Xcode.app
$ ./check project Guitar

usage: check [-h] [--swiftc PATH] project
check: error: unrecognized arguments: Guitar
```

**Comment by lplarson** [comment]
Are you testing on Linux?

**Comment by lplarson** [comment]
Oh, never mind. Try ./check Guitar

**Comment by ArtSabintsev** [comment]
Ah, I'm Swift 3.1. Guess I need to downgrade?

```
$ ./check Guitar
** CHECK **
--- Finding Guitar Swift version compatibility ---
--- Project configured to be compatible with Swift 3.0 ---
--- Checking Guitar platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check failed ---
Expected version:
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9

Current version:
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

error: please select Xcode 8.0 (contains Swift 3.0)
```

**Comment by lplarson** [comment]
Does your project still build against Swift 3.0? If it doesn't, feel free to change the supported version of Swift to 3.1. We accept 3.1 projects.

**Comment by ArtSabintsev** [comment]
Pretty sure it builds for both, but I'll change to 3.1 in the PR, since I don't have a version of Xcode that runs against 3.0 locally.

Seems to work when I made the 3.1 change:

```
./check Guitar
** CHECK **
--- Finding Guitar Swift version compatibility ---
--- Project configured to be compatible with Swift 3.1 ---
--- Checking Guitar platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check succeeded ---
--- Executing build actions ---
$ /Users/Arthur/Documents/oss/swift-source-compat-suite/runner.py --swift-branch swift-3.1-branch --swiftc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects /Users/Arthur/Documents/oss/swift-source-compat-suite/projects.json --include-repos 'path == "Guitar"' --include-actions 'action.startswith("Build")'
PASS: Guitar, 3.1, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- Guitar checked successfully against Swift 3.1 ---
```

**Comment by ArtSabintsev** [comment]
Change has been made.

**Comment by lplarson** [comment]
Thanks!

**Comment by slavapestov** [comment]
Thanks @ArtSabintsev! This should be a nice one for ensuring the new Swift 4 string stuff, when it lands, doesn't break 3.x code!

**Comment by ArtSabintsev** [comment]
My pleasure! Ya, I'm scared/excited for all the Strings changes that'll be coming out! I'll do my best to be on the ball with updating this project as needed.

**Comment by slavapestov** [comment]
@ArtSabintsev The whole point is you don't have to update your project - we want to keep existing code working as much as possible :-)

**Comment by ArtSabintsev** [comment]
I know, I know :) Best of luck with that endeavor!

**Comment by shahmishal** [comment]
@swift-ci Please Test Source Compatibility

**Comment by shahmishal** [comment]
@swift-ci Please Test Source Compatibility

**Comment by ArtSabintsev** [comment]
@shahmishal does that command do anything that causes a visual change/status on this PR? I think @lplarson said this was unsupported at the moment for these types of PRs.

**Comment by shahmishal** [comment]
@ArtSabintsev I am adding new feature to test new projects before adding them to master branch. Please ignore my comment for now.

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by lplarson** [comment]
@swift-ci Please test.

**Comment by lplarson** [comment]
Looks good. Thanks!

**Comment by ArtSabintsev** [comment]
Awesome! Should I make a PR to update the README?

**Comment by lplarson** [comment]
No need. We're going to remove the list of projects in the README and link to the list on Swift.org, which will be updated automatically.

**Comment by ArtSabintsev** [comment]
Ok cool - thanks again!

**Pull request merged**
