### PR TITLE
Update Kitura

### PR DESCRIPTION
**Pull request by mbarnach**
### Pull Request Description

Update the GIT URL and maintainer address for the Kitura Project.

### CODE REVIEW

**Comment by clackary** [comment]
Pinging @dannys42 and @ianpartridge here to make sure this isn't unexpected. Usually the maintainer (of the source compatibility configuration) would add themselves here.

**Comment by ianpartridge** [comment]
I'm fine with this. Thanks for checking.

**Comment by mbarnach** [comment]
Hi guys, indeed sorry, I should have made it more explicit. I've updated the maintainer in the same commit as the URL. This is the same process we are applying also to Cocoapods. Thanks for double checking anyways!

**Comment by clackary** [comment]
@swift-ci test

**Comment by dannys42** [comment]
Works for me.  Thanks all.

**Review by clackary — APPROVED** [review]

**Pull request merged**
