### PR TITLE
MovieSwift appears to be working again

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by justice-adams-apple** [comment]
looks like this is still failing in debug: https://ci.swift.org/job/swift-main-source-compat-suite-debug/426

Taking a look

**Comment by justice-adams-apple** [comment]
This is fixed on main

**Pull request closed without merging**
