### PR TITLE
Xfailing SwiftLint, because SourceKitten needs to be adjsuted to resp…

### PR DESCRIPTION
**Pull request by ematejska**
Xfailing SwiftLint, because SourceKitten needs to be adjusted to respond to IUO rework (apple/swift#12849)

### CODE REVIEW

**Comment by ematejska** [comment]
@swift-ci test source compatibility

**Comment by ematejska** [comment]
@swift-ci Please test source compatibility os x

**Comment by ematejska** [comment]
@swift-ci Please test source compatibility

**Comment by ematejska** [comment]
@swift-ci test

**Comment by jpsim** [comment]
I'm looking to fix this, but do not have access to the radar you're referencing here @ematejska.

Given that the responsibility to fix such `xfails` rest on the project maintainers, why not file tickets on [bugs.swift.org](https://bugs.swift.org) where those maintainers can see them rather than the closed-access radar system?

**Comment by jpsim** [comment]
I found the issue and fixed it upstream, but it will take some time to propagate that to SwiftLint at which point I'll make a PR to remove these xfails.

**Comment by ematejska** [comment]
@jpsim , good point about filing these issues externally.  Will do in the future.  Thank you for fixing up.

**Pull request merged**
