### PR TITLE
Add swift-argument-parser

### PR DESCRIPTION
**Pull request by clackary**
### Pull Request Description

Add https://github.com/apple/swift-argument-parser

### Acceptance Criteria
- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* Apache License, version 2.0
- [x] pass `./project_precommit_check` script run
```
PASS: swift-argument-parser, 5.2, 41f5fe, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- swift-argument-parser checked successfully against Swift 5.2 ---
```

### CODE REVIEW

**Comment by clackary** [comment]
@natecook1000 FYI - Also adding you as maintainer here! Thanks

**Comment by clackary** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Can you also add tag `"tags": "swiftpm"`?

**Comment by clackary** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Comment by clackary** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
This contains only the merge conflict fix, and the previous commit was tested successfully.

Also, json format was verified in the current trigger. 

`./swift-source-compat-suite/utils/format_projects_list.py swift-source-compat-suite/projects.json`

merging the PR.

**Pull request merged**
